[package]
name = "dao_views"
version = "1.0.0"
authors = []

[addresses]

SLEEP = "0xe3604080ae874ea9c4b770744fa1a713d94e1d4ec0c5b7aba4ad5195de7841f8"
dao_tokens = "0xe3604080ae874ea9c4b770744fa1a713d94e1d4ec0c5b7aba4ad5195de7841f8"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.hoglet_dao]
local = "../dao_factory"

[dependencies.dao_libs]
local = "../dao_libs"
