[package]
name = "dao_views"
version = "1.0.0"
authors = []

[addresses]

COLD = "0x738ba0cff4cbecdf01cdb22b4b49c9d226677d798f90514baed32d937fc1acee"
dao_tokens = "0x738ba0cff4cbecdf01cdb22b4b49c9d226677d798f90514baed32d937fc1acee"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.hoglet_dao]
local = "../dao_factory"

[dependencies.dao_libs]
local = "../dao_libs"
