[package]
name = "dao_libs"
version = "1.0.0"

[addresses]

HOG = "0x3ec6be8be7d00c5e778a76ea9a3cf8650ccb7cb0e6fcce36653beed63198cc9f"
dao_libs = "0xdb4cf49e9ed210625dfc497a125a15f1b37bc138629611002c5a660fbe72bb07"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"
