[package]
name = "dao_libs"
version = "1.0.0"

[addresses]

HOPE = "0x9a63b4ff0e6ec6cefa033bd323bd2ea6f6cf2a3c580ae5ba076f087c7d12ec53"
dao_libs = "0xf492fbab916043a2e2e6138c54a767ba2373b5900302d1053cf8272c2a4f4790"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"
