[package]
name = "dao_tokens"
version = "1.0.0"
authors = []

[addresses]

HOG = "0x3ec6be8be7d00c5e778a76ea9a3cf8650ccb7cb0e6fcce36653beed63198cc9f"
dao_tokens = "0x083387c3fec5279835cd55d009dba0265fc9c30fd727b47c0c5ff93da18719a0"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"
