[package]
name = "dao_router"
version = "1.0.0"

[addresses]

HOPE = "0x9a63b4ff0e6ec6cefa033bd323bd2ea6f6cf2a3c580ae5ba076f087c7d12ec53"
dao_router = "0xaf6b500aa29614eed0be9489f2c0a2f9cd68ed712139965e0210a996589e0596"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.hoglet_dao]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_factory"

[dependencies.hoglet_core]
git = "https://github.com/hoglet-DAO/hoglet_launcher.git"
rev = "main"
subdir = "testnet/hoglet_core"

[dependencies.nft_wrap]
git = "https://github.com/hoglet-DAO/nft_wrapper.git"
rev = "main"
