[package]
name = "dao_router"
version = "1.0.0"

[addresses]

HOG = "0x3ec6be8be7d00c5e778a76ea9a3cf8650ccb7cb0e6fcce36653beed63198cc9f"
dao_router = "0xdd402ffe6331378c5e875af86065a21f2f74dd29ecfcf1a19cb7e7843297e496"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.hoglet_dao]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "mainnet/dao_factory"

[dependencies.hoglet_core]
git = "https://github.com/hoglet-DAO/hoglet_launcher.git"
rev = "main"
subdir = "mainnet/hoglet_core"

[dependencies.nft_wrap]
git = "https://github.com/hoglet-DAO/nft_wrapper.git"
rev = "main"
