[package]
name = "dao_router"
version = "1.0.0"

[addresses]

HOGLET = "0x17aecc0a267c77a70f51db8070f504bce55d64de886e675b52bd9143729897d9"
dao_router = "0x13c90f722518a73544acbe3c4c7a7ac63a1922ee3e6d34c4d6220a5e5bf4f45d"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.hoglet_dao]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "mainnet/dao_factory"

[dependencies.hoglet_core]
git = "https://github.com/hoglet-DAO/hoglet_launcher.git"
rev = "main"
subdir = "mainnet/hoglet_core"

[dependencies.nft_wrap]
git = "https://github.com/hoglet-DAO/nft_wrapper.git"
rev = "main"
