[package]
name = "hoglet_dao"
version = "1.0.0"
authors = []

[addresses]

FUEL = "0x6c974af09deb94ae93708bfe0216db7406b974ce3189af96ba838dd723d5d768"
dao_factory = "0x6c974af09deb94ae93708bfe0216db7406b974ce3189af96ba838dd723d5d768"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "b710f2df13c46ba8ec7c9aec2a5ed78bcfd4b3ce"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "b710f2df13c46ba8ec7c9aec2a5ed78bcfd4b3ce"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
