[package]
name = "hoglet_dao"
version = "1.0.0"
authors = []

[addresses]

POWER = "0xe9030ffafb1fd67a3311ad756c3e7435b6d50519b2c571f400f10462c56507cd"
dao_factory = "0xe9030ffafb1fd67a3311ad756c3e7435b6d50519b2c571f400f10462c56507cd"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "b710f2df13c46ba8ec7c9aec2a5ed78bcfd4b3ce"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "b710f2df13c46ba8ec7c9aec2a5ed78bcfd4b3ce"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
