[package]
name = "dao_tokens"
version = "1.0.0"
authors = []

[addresses]

HOGLET = "0x17aecc0a267c77a70f51db8070f504bce55d64de886e675b52bd9143729897d9"
dao_tokens = "0x1eba8465567e01718a19b95ce04ae2b7d5b7f81d41ce2683ee72e97a4ddc8657"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"
