[package]
name = "dao_views"
version = "1.0.0"
authors = []

[addresses]

HOG = "0x3ec6be8be7d00c5e778a76ea9a3cf8650ccb7cb0e6fcce36653beed63198cc9f"
dao_views = "0xc3d3e1cee546bfae35c03e0f6f21469d2161dc405315a5f55949ddae423ddcda"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.hoglet_dao]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_factory"

[dependencies.dao_libs]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_libs"
