[package]
name = "dao_genesis"
version = "1.0.0"

SLEEP = "0xe3604080ae874ea9c4b770744fa1a713d94e1d4ec0c5b7aba4ad5195de7841f8"
dao_factory = "0xe3604080ae874ea9c4b770744fa1a713d94e1d4ec0c5b7aba4ad5195de7841f8"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.hoglet_dao]
local = "../dao_factory"