[package]
name = "dao_genesis"
version = "1.0.0"

HOGLET = "0x17aecc0a267c77a70f51db8070f504bce55d64de886e675b52bd9143729897d9"
dao_factory = "0x17aecc0a267c77a70f51db8070f504bce55d64de886e675b52bd9143729897d9"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.hoglet_dao]
local = "../dao_factory"