[package]
name = "dao_tax_router"
version = "1.0.0"

[addresses]

HOG = "0x3ec6be8be7d00c5e778a76ea9a3cf8650ccb7cb0e6fcce36653beed63198cc9f"
dao_tax_router = "0x7d6f97a1840d61eb9babd470afb4bd07d2676ffc26a06f59b5c663fd51ae6527"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.dao_tokens]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_tokens"