[package]
name = "hoglet_dao"
version = "1.0.0"
authors = []

[addresses]

HOG = "0x3ec6be8be7d00c5e778a76ea9a3cf8650ccb7cb0e6fcce36653beed63198cc9f"
dao_factory = "0x94308f41c5a3dbdcc04fa0cc24b1e8dd2b72723142d03292310104f731a83606"
dao_genesis = "0x643e0533832d6048baac063fd0622f92d26fa0fc6751cc22ed46bc857a307c9f"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.dfmm_framework]
git = "https://github.com/hoglet-DAO/POEL_contracts.git"
rev = "main"
subdir = "testnet"

[dependencies.dao_libs]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_libs"

[dependencies.dao_tax_router]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_tax_router"

[dependencies.dao_tokens]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_tokens"

[dependencies.dao_scripts]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_scripts"

[dev-dependencies]
